ignore:
  - GHSA-6c3j-c64m-qhgq
  - GHSA-gxr4-xjj5-5px2
  - GHSA-jpcq-cgw6-v4j6
  - GHSA-rmxg-73gg-4p98
  - GHSA-jpcq-cgw6-v4j6
  - GHSA-2gwj-7jmv-h26r
  - GHSA-2m34-jcjv-45xf
  - GHSA-53qw-q765-4fww
  - GHSA-68w8-qjq3-2gfm
  - GHSA-6cw3-g6wv-c2xv
  - GHSA-8c5j-9r9f-c6w8
  - GHSA-95rw-fx8r-36v6
  - GHSA-fr28-569j-53c4
  - GHSA-fvgf-6h6h-3322
  - GHSA-jrh2-hc4r-7jwx
  - GHSA-m6gj-h9gm-gw44
  - GHSA-p99v-5w3c-jqq9
  - GHSA-qm57-vhq3-3fwf
  - GHSA-rxjp-mfm9-w4wr
  - GHSA-v6rh-hp5x-86rv
  - GHSA-w24h-v9qh-8gxj
  - GHSA-wpjr-j57x-wxfw
  - GHSA-xgxc-v2qg-chmh
  - GHSA-58c7-px5v-82hh