version: "3"

services:
    backend: &backend
        stdin_open: true
        tty: true
        build: .
        env_file: .env
        environment:
          - DEBUG=true
          - DATABASE_URL=postgres://postgres:postgres@database/postgres
        ports:
          - 8000:8000
        volumes:
            - "./:/app:z"
        links:
            - database
            - mail
        depends_on:
          database:
            condition: service_healthy
    database:
        image: postgres:14
        environment:
          - "POSTGRES_PASSWORD=postgres"
        ports:
          - 5432:5432
        healthcheck:
          test: ["CMD", "/usr/bin/pg_isready", "-h", "database", "-p", "5432", "-U", "postgres", "-d", "postgres"]
          interval: 5s
          timeout: 10s
          retries: 120
    mail:
        image: djfarrelly/maildev
        ports:
          - 1025:1025
        command: bin/maildev --web 1025 --smtp 25
