# fly.toml file generated for nzsl-signbank on 2022-02-09T14:06:36+13:00

app = "nzsl-signbank"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  private_network = true

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 8000

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

