# Generated by Django 5.2.16 on 2026-07-29 02:05

import signbank.video.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_glossvideotoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossvideo',
            name='videofile',
            field=models.FileField(help_text='Video file.', storage=signbank.video.models.GlossVideoDynamicStorage(), upload_to=signbank.video.models.glossvideo_upload_to, verbose_name='Video file'),
        ),
    ]
