name: Deployment
on:
  push:
    branches:
      - feature/run-locally
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the docker-compose stack
      run: docker-compose up -d
    - name: Check running containers
      run: docker ps -a
    - name: Check logs
      run: docker-compose logs backend
    - name: Run migrations
      run: |
        docker-compose run backend python3 bin/develop.py migrate --noinput
    - name: Run test suite
      run: docker-compose run backend python3 bin/develop.py test