name: Deployment
on:
  push:
    branches:
      - feature/run-locally
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy app
      environment: Main
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run: cp signbank/settings/settings_secret.py.template signbank/settings/settings_secret.py
        - uses: superfly/flyctl-actions@1.1
          with:
            args: "deploy"
